apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 60.1.0 # Use a stable chart version
    helm:
      releaseName: prometheus
      values: |
        grafana:
          adminUser: wisecow
          adminPassword: wisecow
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - grafana.checkmypro.online
            tls:
              - secretName: grafana-secret-tls
                hosts:
                  - grafana.checkmypro.online
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
